version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        port: ${PORT}
    volumes:
      - ./:/usr/src/app
    expose:
      - ${PORT}
    ports:
      - ${PORT}:${PORT}
    env_file: .env
